Basic readers
quantumlib/Stim pull request #131
Opened 2021-08-11 05:08 UTC by viathor

The API is simple, but supports rather varied file formats (one vs many measure records per file, known vs unknown record length) in a consistent way.

Tests fall into three groups: counterparts to tests for writers, write-read-compare tests and additional tests for multi-record file formats.

Follow-ups:
* benchmarking tests for the readers,
* integration with `MeasureRecord`,
* support for PTB64 file format,
* read counterpart to `write_table_data`,
* possible refactoring of `write_table_data` to fit it into `MeasureRecordWriters` and similar for the read side (contingent on a fix for the performance regression this is causing).

2021-08-11 05:24 UTC, Strilanc requested changes
Details look nice, but I want to change one of the API design decisions.

2021-08-11 05:24 UTC, Strilanc commented on src/io/measure_record_reader.cc
> +        throw std::runtime_error("Character code " + std::to_string(payload) + " does not encode a bit");
Say `"Expected '0' or '1' because input format was specified as '01'."`

2021-08-11 05:24 UTC, Strilanc commented on src/io/measure_record_reader.cc
> +    size_t k = data.ptr_end - data.ptr_start;
`data.size()`

2021-08-11 05:24 UTC, Strilanc commented on src/io/measure_record_reader.h
> +/// HITS and DETS encode any number of records. File formats 01, B8 and R8 encode the length of each record.
I think the reader should *always* know how long the record is going to be. The length should be required in order to create the reader. The 01 and DETS and other length-in-data readers use this information for *verifying* that the number of records they get is correct. The reader should be responsible for length validation; not the caller.

2021-08-16 23:18 UTC, viathor commented
PTAL. I plan to add one more set of tests, but these depend on the interface of the DETS reader which I'd like feedback on (especially, the new ctor signature).

Broken tests are due to #133 which will be fixed once #134 is merged.

2021-08-17 05:04 UTC, viathor commented
As expected, merging #134 have caused all tests to pass.

2021-08-25 16:34 UTC, viathor commented
Friendly ping :-)

2021-09-01 00:32 UTC, Strilanc approved these changes

2021-09-01 00:32 UTC, merged

2021-09-01 00:33 UTC, viathor commented
\o/