Documentation corrections
quantumlib/Stim pull request #138
Opened 2021-09-05 21:52 UTC by speller26

* Correct "principle square root" to "principal square root"
* Correct the dagger gate docs to read "Adjoint of the principal square root"

2021-09-05 22:32 UTC, speller26 commented
@googlebot I signed it!

2021-09-05 23:12 UTC, Strilanc commented on src/circuit/gate_data_period_4.cc
> +Adjoint of the principal square root of Y gate.
This isn't the adjoint.

2021-09-05 23:16 UTC, Strilanc requested changes

2021-09-05 23:16 UTC, Strilanc commented on src/circuit/gate_data_period_4.cc
> +Adjoint of the principal square root of Y gate.
Also update SQRT_X_DAG's documentation.

2021-09-05 23:18 UTC, Strilanc commented
Thanks for the typo fix. I always get that particular pair of homonyms mixed up. There's just a change to SQRT_X_DAG missing.

2021-09-06 07:07 UTC, speller26 commented on src/circuit/gate_data_period_4.cc
> +Adjoint of the principal square root of Y gate.
Done!

2021-09-06 08:38 UTC, Strilanc approved these changes

2021-09-06 08:41 UTC, merged